# Use root/example as user/password credentials
version: "3.1"

x-environment: &default-environment
  RABBITMQ_URL: amqp://rabbitmq:rabbitmq@rabbitmq:5672/
  MONGO_URL: mongodb://root:example@mongo:27017/

services:
  rabbitmq:
    ports:
      - 5672:5672
      - 15672:15672
    image: rabbitmq:latest
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    networks:
      - doctor-booking-network

  doctor-booking-client:
    build: ./doctor-customer
    image: rozanfa/doctor-booking-client:latest
    container_name: doctor-booking-client
    ports:
      - "3001:3001"
    networks:
      - doctor-booking-network
    depends_on:
      rabbitmq:
        condition: service_started
    restart: unless-stopped
    environment:
      PORT: 3001
      <<: *default-environment
    volumes:
      - ./doctor-customer/src:/usr/src/app/src

  reservation-general:
    build: ./reservation-general
    image: rozanfa/reservation-general
    container_name: reservation-general
    ports:
      - "8081:8081"
    environment:
      <<: *default-environment
    networks:
      - doctor-booking-network
    restart: always
    volumes:
      - ./reservation-general:/app
    
  reservation-vaccination:
    build: ./reservation-vaccination
    image: rozanfa/reservation-vaccination
    container_name: reservation-vaccination
    ports:
      - "8080:8080"
    environment:
      <<: *default-environment
    networks:
      - doctor-booking-network
    restart: always
    volumes:
      - ./reservation-vaccination:/app

  fe-booking-system:
    build: ./fe-booking-system
    image: rozanfa/fe-booking-system
    container_name: fe-booking-system
    ports:
      - "3000:3000"
    environment:
      VITE_BASE_REST_URL: http://localhost:3001
    volumes:
      - ./fe-booking-system/src:/app/src

networks:
  doctor-booking-network:
    driver: bridge